CREATE TABLE langile_typ (
    nan VARCHAR2(10) PRIMARY KEY,
    izena VARCHAR2(50) NOT NULL,
    abizena VARCHAR2(50) NOT NULL,
    kontratatze_data DATE NOT NULL,
    soldata_oinarria NUMBER(10, 2) NOT NULL,
    mota VARCHAR2(20) CHECK (mota IN ('ADMINISTRARI', 'TEKNIKARI')) NOT NULL
);

CREATE TABLE helbide_typ (
    langile_nan VARCHAR2(10) PRIMARY KEY,
    helbidea VARCHAR2(100),
    postakodea VARCHAR2(10),
    herria VARCHAR2(50),
    probintzia VARCHAR2(50),
    CONSTRAINT fk_helbide_langile FOREIGN KEY (langile_nan)
        REFERENCES langile_typ(nan)
        ON DELETE CASCADE
);

CREATE TABLE telefono_typ (
    telefono_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    langile_nan VARCHAR2(10) NOT NULL,
    telefono_zenbakia VARCHAR2(15) NOT NULL,
    CONSTRAINT fk_telefono_langile FOREIGN KEY (langile_nan)
        REFERENCES langile_typ(nan)
        ON DELETE CASCADE
);

CREATE TABLE administrari_typ (
    langile_nan VARCHAR2(10) PRIMARY KEY,
    ikasketak VARCHAR2(100),
    CONSTRAINT fk_admin_langile FOREIGN KEY (langile_nan)
        REFERENCES langile_typ(nan)
        ON DELETE CASCADE
);

CREATE TABLE teknikari_typ (
    langile_nan VARCHAR2(10) PRIMARY KEY,
    eginkizuna VARCHAR2(100),
    CONSTRAINT fk_teknikari_langile FOREIGN KEY (langile_nan)
        REFERENCES langile_typ(nan)
        ON DELETE CASCADE
);