CREATE TABLE langile_typ (
    nan VARCHAR2(10) PRIMARY KEY,
    izena VARCHAR2(50) NOT NULL,
    abizena VARCHAR2(50) NOT NULL,
    kontratatze_data DATE NOT NULL,
    soldata_oinarria NUMBER(10, 2) NOT NULL,
    mota VARCHAR2(20) CHECK (mota IN ('ADMINISTRARI', 'TEKNIKARI')) NOT NULL
);

CREATE TABLE helbide_typ (
    langile_nan VARCHAR2(10) PRIMARY KEY,
    helbidea VARCHAR2(100),
    postakodea VARCHAR2(10),
    herria VARCHAR2(50),
    probintzia VARCHAR2(50),
    CONSTRAINT fk_helbide_langile FOREIGN KEY (langile_nan)
        REFERENCES langile_typ(nan)
        ON DELETE CASCADE
);

CREATE TABLE telefono_typ (
    telefono_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    langile_nan VARCHAR2(10) NOT NULL,
    telefono_zenbakia VARCHAR2(15) NOT NULL,
    CONSTRAINT fk_telefono_langile FOREIGN KEY (langile_nan)
        REFERENCES langile_typ(nan)
        ON DELETE CASCADE
);

CREATE TABLE administrari_typ (
    langile_nan VARCHAR2(10) PRIMARY KEY,
    ikasketak VARCHAR2(100),
    CONSTRAINT fk_admin_langile FOREIGN KEY (langile_nan)
        REFERENCES langile_typ(nan)
        ON DELETE CASCADE
);

CREATE TABLE teknikari_typ (
    langile_nan VARCHAR2(10) PRIMARY KEY,
    eginkizuna VARCHAR2(100),
    CONSTRAINT fk_teknikari_langile FOREIGN KEY (langile_nan)
        REFERENCES langile_typ(nan)
        ON DELETE CASCADE
);

INSERT INTO langile_typ (nan, izena, abizena, kontratatze_data, soldata_oinarria, mota)
VALUES ('11111111A', 'Mikel', 'Clavero', TO_DATE('2020-05-15', 'YYYY-MM-DD'), 25000.00, 'ADMINISTRARI');

INSERT INTO langile_typ (nan, izena, abizena, kontratatze_data, soldata_oinarria, mota)
VALUES ('22222222B', 'Xabier', 'Lopez', TO_DATE('2023-10-01', 'YYYY-MM-DD'), 22000.00, 'ADMINISTRARI');

INSERT INTO langile_typ (nan, izena, abizena, kontratatze_data, soldata_oinarria, mota)
VALUES ('33333333C', 'Sean', 'Alberdi', TO_DATE('2018-01-01', 'YYYY-MM-DD'), 30000.00, 'TEKNIKARI');

INSERT INTO langile_typ (nan, izena, abizena, kontratatze_data, soldata_oinarria, mota)
VALUES ('44444444D', 'Erlantz', 'García', TO_DATE('2024-01-20', 'YYYY-MM-DD'), 28000.00, 'TEKNIKARI');

INSERT INTO helbide_typ (langile_nan, helbidea, postakodea, herria, probintzia)
VALUES ('11111111A', 'Kale Nagusia 1', '48920', 'Portugalete', 'Bizkaia');

INSERT INTO helbide_typ (langile_nan, helbidea, postakodea, herria, probintzia)
VALUES ('22222222B', 'Kale Nagusia 2', '48980', 'Santurtzi', 'Bizkaia');

INSERT INTO helbide_typ (langile_nan, helbidea, postakodea, herria, probintzia)
VALUES ('33333333C', 'Kale Nagusia 3', '48920', 'Portugalete', 'Bizkaia');

INSERT INTO helbide_typ (langile_nan, helbidea, postakodea, herria, probintzia)
VALUES ('44444444D', 'Kale Nagusia 4', '48980', 'Santurtzi', 'Bizkaia');

INSERT INTO administrari_typ (langile_nan, ikasketak)
VALUES ('11111111A', 'Informatika');

INSERT INTO administrari_typ (langile_nan, ikasketak)
VALUES ('22222222B', 'Segurtasuna');

INSERT INTO teknikari_typ (langile_nan, eginkizuna)
VALUES ('33333333C', 'Serbitzu Instalazioak');

INSERT INTO teknikari_typ (langile_nan, eginkizuna)
VALUES ('44444444D', 'Aplikazioen Mantenimendua');

INSERT INTO telefono_typ (langile_nan, telefono_zenbakia)
VALUES ('11111111A', '600111111');

INSERT INTO telefono_typ (langile_nan, telefono_zenbakia)
VALUES ('11111111A', '944111111');

INSERT INTO telefono_typ (langile_nan, telefono_zenbakia)
VALUES ('22222222B', '600222222');

INSERT INTO telefono_typ (langile_nan, telefono_zenbakia)
VALUES ('33333333C', '600333333');

INSERT INTO telefono_typ (langile_nan, telefono_zenbakia)
VALUES ('44444444D', '600444444');

INSERT INTO telefono_typ (langile_nan, telefono_zenbakia)
VALUES ('44444444D', '943555555');

Charlar

Nueva Conversación

🤓 Explica algo complejo

Explica la Inteligencia Artificial de tal manera que pueda explicársela a mi hijo de seis años.


🧠 Obtén sugerencias y crea nuevas ideas

Por favor, dame las mejores 10 ideas para viajar alrededor del mundo".


💭 Traducir, resumir, corregir gramática y más...

Traduce "Te amo", al francés.



AITOPIA


AITOPIA
coin image
10
Actualizar




CREATE TABLE langile_typ (
    nan VARCHAR2(10) PRIMARY KEY,
    izena VARCHAR2(50) NOT NULL,
    abizena VARCHAR2(50) NOT NULL,
    kontratatze_data DATE NOT NULL,
    soldata_oinarria NUMBER(10, 2) NOT NULL,
    mota VARCHAR2(20) CHECK (mota IN ('ADMINISTRARI', 'TEKNIKARI')) NOT NULL
);

CREATE TABLE helbide_typ (
    langile_nan VARCHAR2(10) PRIMARY KEY,
    helbidea VARCHAR2(100),
    postakodea VARCHAR2(10),
    herria VARCHAR2(50),
    probintzia VARCHAR2(50),
    CONSTRAINT fk_helbide_langile FOREIGN KEY (langile_nan)
        REFERENCES langile_typ(nan)
        ON DELETE CASCADE
);

CREATE TABLE telefono_typ (
    telefono_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    langile_nan VARCHAR2(10) NOT NULL,
    telefono_zenbakia VARCHAR2(15) NOT NULL,
    CONSTRAINT fk_telefono_langile FOREIGN KEY (langile_nan)
        REFERENCES langile_typ(nan)
        ON DELETE CASCADE
);

CREATE TABLE administrari_typ (
    langile_nan VARCHAR2(10) PRIMARY KEY,
    ikasketak VARCHAR2(100),
    CONSTRAINT fk_admin_langile FOREIGN KEY (langile_nan)
        REFERENCES langile_typ(nan)
        ON DELETE CASCADE
);

CREATE TABLE teknikari_typ (
    langile_nan VARCHAR2(10) PRIMARY KEY,
    eginkizuna VARCHAR2(100),
    CONSTRAINT fk_teknikari_langile FOREIGN KEY (langile_nan)
        REFERENCES langile_typ(nan)
        ON DELETE CASCADE
);

INSERT INTO langile_typ (nan, izena, abizena, kontratatze_data, soldata_oinarria, mota)
VALUES ('11111111A', 'Mikel', 'Clavero', TO_DATE('2020-05-15', 'YYYY-MM-DD'), 25000.00, 'ADMINISTRARI');

INSERT INTO langile_typ (nan, izena, abizena, kontratatze_data, soldata_oinarria, mota)
VALUES ('22222222B', 'Xabier', 'Lopez', TO_DATE('2023-10-01', 'YYYY-MM-DD'), 22000.00, 'ADMINISTRARI');

INSERT INTO langile_typ (nan, izena, abizena, kontratatze_data, soldata_oinarria, mota)
VALUES ('33333333C', 'Sean', 'Alberdi', TO_DATE('2018-01-01', 'YYYY-MM-DD'), 30000.00, 'TEKNIKARI');

INSERT INTO langile_typ (nan, izena, abizena, kontratatze_data, soldata_oinarria, mota)
VALUES ('44444444D', 'Erlantz', 'García', TO_DATE('2024-01-20', 'YYYY-MM-DD'), 28000.00, 'TEKNIKARI');

INSERT INTO helbide_typ (langile_nan, helbidea, postakodea, herria, probintzia)
VALUES ('11111111A', 'Kale Nagusia 1', '48920', 'Portugalete', 'Bizkaia');

INSERT INTO helbide_typ (langile_nan, helbidea, postakodea, herria, probintzia)
VALUES ('22222222B', 'Kale Nagusia 2', '48980', 'Santurtzi', 'Bizkaia');

INSERT INTO helbide_typ (langile_nan, helbidea, postakodea, herria, probintzia)
VALUES ('33333333C', 'Kale Nagusia 3', '48920', 'Portugalete', 'Bizkaia');

INSERT INTO helbide_typ (langile_nan, helbidea, postakodea, herria, probintzia)
VALUES ('44444444D', 'Kale Nagusia 4', '48980', 'Santurtzi', 'Bizkaia');

INSERT INTO administrari_typ (langile_nan, ikasketak)
VALUES ('11111111A', 'Informatika');

INSERT INTO administrari_typ (langile_nan, ikasketak)
VALUES ('22222222B', 'Segurtasuna');

INSERT INTO teknikari_typ (langile_nan, eginkizuna)
VALUES ('33333333C', 'Serbitzu Instalazioak');

INSERT INTO teknikari_typ (langile_nan, eginkizuna)
VALUES ('44444444D', 'Aplikazioen Mantenimendua');

INSERT INTO telefono_typ (langile_nan, telefono_zenbakia)
VALUES ('11111111A', '600111111');

INSERT INTO telefono_typ (langile_nan, telefono_zenbakia)
VALUES ('11111111A', '944111111');

INSERT INTO telefono_typ (langile_nan, telefono_zenbakia)
VALUES ('22222222B', '600222222');

INSERT INTO telefono_typ (langile_nan, telefono_zenbakia)
VALUES ('33333333C', '600333333');

INSERT INTO telefono_typ (langile_nan, telefono_zenbakia)
VALUES ('44444444D', '600444444');

INSERT INTO telefono_typ (langile_nan, telefono_zenbakia)
VALUES ('44444444D', '943555555');

CREATE OR REPLACE FUNCTION soldata_totala_kalkulatu (
    p_soldata_oinarria IN NUMBER,
    p_kontratatze_data IN DATE
) RETURN NUMBER
IS
    antzinatasun_urteak INTEGER := 0;
    soldata_totala_kalk NUMBER := 0;
BEGIN
    IF p_kontratatze_data IS NOT NULL THEN
        antzinatasun_urteak := FLOOR(MONTHS_BETWEEN(SYSDATE, p_kontratatze_data) / 12);
        IF antzinatasun_urteak < 0 THEN
            antzinatasun_urteak := 0;
        END IF;
    END IF;

    soldata_totala_kalk := p_soldata_oinarria * (1 + antzinatasun_urteak * 0.02);

    RETURN ROUND(soldata_totala_kalk, 2);
END soldata_totala_kalkulatu;
/ 

SELECT
    l.nan AS nan_zenbakia,
    l.izena,
    l.abizena,
    
    h.helbidea || ', ' || h.postakodea || ' (' || h.probintzia || ')' AS helbidea_osoa,
    h.herria AS herria,
    
    NVL(
        (
            SELECT LISTAGG(t.telefono_zenbakia, ', ')
                   WITHIN GROUP (ORDER BY t.telefono_zenbakia)
            FROM telefono_typ t
            WHERE t.langile_nan = l.nan
        ),
        'Ez du telefonorik'
    ) AS telefonoak,
    
    TO_CHAR(l.soldata_oinarria, '999G999D00') AS soldata_oinarria,
    TO_CHAR(soldata_totala_kalkulatu(l.soldata_oinarria, l.kontratatze_data), '999G999D00') AS soldata_totala

FROM 
    langile_typ l
    JOIN administrari_typ a ON l.nan = a.langile_nan
    JOIN helbide_typ h ON l.nan = h.langile_nan;


